// src/Components/Attendance.js
import React, { useEffect, useState } from 'react';
import axios from 'axios';
//import { attendanceData } from './Router';

const userData = [
        {
          "id": 1,
          "prenom": "Preeti",
          "nom": "Marshall",
          "courriel": "marypa_27@example.com",
          "telephone": "6136122233",
          "telephoneUrgence": "6132779293",
          "adresse": "617 Du Buisson Cres",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "J4A3A4",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Hugo",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 2,
          "prenom": "Matthew",
          "nom": "Maisonneuve",
          "courriel": "matt.rozak@example.com",
          "telephone": "6138515442",
          "telephoneUrgence": "6132515552",
          "adresse": "520 Arum Terrace",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "J'accepte",
          "codePostal": "J4A 1E6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Winifred ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 3,
          "prenom": "Anik",
          "nom": "St-Denis",
          "courriel": "anikkahrer@example.com",
          "telephone": "6134020052",
          "telephoneUrgence": "6135079052",
          "adresse": "1508 Delia Crescent",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A 2Y3",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Alek ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 4,
          "prenom": "Andree",
          "nom": "Ignacz",
          "courriel": "andree.seguin27@example.com",
          "telephone": "6132008220",
          "telephoneUrgence": "6132992770",
          "adresse": "2735 Lockwood Lane",
          "numeroSuite": "",
          "ville": "Cumberland",
          "province": "Ontario",
          "codePostal": "J4C 1B6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Felix ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 5,
          "prenom": "Gaby",
          "nom": "Richard",
          "courriel": "gabycjovic@example.com",
          "telephone": "2280286138",
          "telephoneUrgence": "7729226132",
          "adresse": "6144 Lariviere",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "Y2W1C6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Maxwell",
          "age": 5,
          "besoinsSpeciaux": "Maxwell a un EpiPen pour le sesame. Si c?est possible, il aimerait etre dans la meme groupe que son amie Oscar (Rozak).  Merci, Gaby"
        },
        {
          "id": 6,
          "prenom": "Annie",
          "nom": "Bouvier",
          "courriel": "famillepickering@example.com",
          "telephone": "613-602-5514",
          "telephoneUrgence": "613-222-2003",
          "adresse": "11 cottimgham Street",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "On",
          "codePostal": "J2G6h7",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Vienna ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 7,
          "prenom": "Elizabeth",
          "nom": "Tetreault",
          "courriel": "ferniegirl@example.com",
          "telephone": "6132624565",
          "telephoneUrgence": "6137625565",
          "adresse": "511 Ponthieu Circle",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2W0N5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Hazel ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 8,
          "prenom": "Annie",
          "nom": "corley",
          "courriel": "anniecarroll14@example.com",
          "telephone": "613-255-2265",
          "telephoneUrgence": "613-255-7265",
          "adresse": "73 Highwood Pvt",
          "numeroSuite": "Highwood",
          "ville": "Ottawa",
          "province": "on",
          "codePostal": "Y2J 4X6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Loic",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 9,
          "prenom": "Catherine",
          "nom": "Jundi",
          "courriel": "cf.thibodeau@example.com",
          "telephone": "6132050400",
          "telephoneUrgence": "6132950509",
          "adresse": "1490, Baker Rd",
          "numeroSuite": "",
          "ville": "Casselman",
          "province": "Ontario",
          "codePostal": "J0A1M0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Gabriel",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 10,
          "prenom": "Julie",
          "nom": "Tabbasum",
          "courriel": "juaude@example.com",
          "telephone": "6136804202",
          "telephoneUrgence": "6136006067",
          "adresse": "1950 Summerfields Crescent",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 7B5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Juliet ",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 11,
          "prenom": "Sophie-Catherine",
          "nom": "Groulx",
          "courriel": "sc.menard@example.com",
          "telephone": "6138301260",
          "telephoneUrgence": "6135572277",
          "adresse": "1341 Caserta Place",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "J4A 3C1",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Maxime ",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 12,
          "prenom": "Stephanie",
          "nom": "Bazinet",
          "courriel": "stephanie-laplante@example.com",
          "telephone": "6130862320",
          "telephoneUrgence": "6135571722",
          "adresse": "1722 Country Walk Dr",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C0C9",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Zoe ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 13,
          "prenom": "Andreanne",
          "nom": "Burk",
          "courriel": "andreanne_com@example.com",
          "telephone": "6132012860",
          "telephoneUrgence": "6132917269",
          "adresse": "455 solstice way",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A0V0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Florence ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 14,
          "prenom": "Marianne",
          "nom": "Rozon",
          "courriel": "rachel_4nier@example.com",
          "telephone": "6138622461",
          "telephoneUrgence": "6139262561",
          "adresse": "1859 Montmere Ave",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A0L7",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Isabelle ",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 15,
          "prenom": "Rachel",
          "nom": "Habib",
          "courriel": "rachel_4nier@example.com",
          "telephone": "613-204-6526",
          "telephoneUrgence": "353-597-5667",
          "adresse": "866 Contour Street",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "Y2W 0G6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Laken",
          "age": 9,
          "besoinsSpeciaux": "Laken a la fibrose kystique et doit prendre des enzymes digestive avec les repas et collations."
        },
        {
          "id": 16,
          "prenom": "Christina",
          "nom": "Vaziri",
          "courriel": "ctinasantos@example.com",
          "telephone": "613-618-8600",
          "telephoneUrgence": "613-612-2699",
          "adresse": "1419 Hayes",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2E 3M0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Selena ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 17,
          "prenom": "Natasha",
          "nom": "Laidlaw",
          "courriel": "natashasauve11@example.com",
          "telephone": "6138255445",
          "telephoneUrgence": "6132755555",
          "adresse": "1673 Country Walk Dr",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 0E1",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Mikaela ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 18,
          "prenom": "Michelle",
          "nom": "Lyons",
          "courriel": "michelle.raffel@example.com",
          "telephone": "6132205432",
          "telephoneUrgence": "6137205532",
          "adresse": "6594 Richer",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C3G4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Elizabeth ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 19,
          "prenom": "Mylene",
          "nom": "Theoret",
          "courriel": "myl_03@example.com",
          "telephone": "8102230323",
          "telephoneUrgence": "6132122395",
          "adresse": "351 Nagel Avenue",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2E 1R0",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Emile ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 20,
          "prenom": "Nathalie",
          "nom": "Sylvestre",
          "courriel": "rachel_4nier@example.com",
          "telephone": "6136140021",
          "telephoneUrgence": "6136159971",
          "adresse": "728 Halstead street",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2G1M6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Kalina",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 21,
          "prenom": "Stephanie",
          "nom": "Lemieux",
          "courriel": "stephanie.jasmin@example.com",
          "telephone": "613-321-4540",
          "telephoneUrgence": "613-371-5559",
          "adresse": "1860 hunters run drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "Y2c 6x2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Mikael ",
          "age": 5,
          "besoinsSpeciaux": "Dans le meme groupe que son ami Elias Castilla svp."
        },
        {
          "id": 22,
          "prenom": "marie-claire",
          "nom": "Roy",
          "courriel": "marieclaire.castilla@example.com",
          "telephone": "6138508311",
          "telephoneUrgence": "6132592311",
          "adresse": "2219 Onyx St",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "J0A 3H0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Elias ",
          "age": 4,
          "besoinsSpeciaux": "Dans le groupe de Michael s.v.p"
        },
        {
          "id": 23,
          "prenom": "Jacynthe",
          "nom": "Gaudreau",
          "courriel": "jcarrierelalonde@example.com",
          "telephone": "6133018482",
          "telephoneUrgence": "6133012522",
          "adresse": "1000 Bateau Place",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2C 2N2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Zacharie ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 24,
          "prenom": "Julie",
          "nom": "BELANGER",
          "courriel": "julie.donais@example.com",
          "telephone": "6138020123",
          "telephoneUrgence": "6132070173",
          "adresse": "1001 Driftwood cres",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2C 2N9",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Zachary ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 25,
          "prenom": "Jean-Pierre",
          "nom": "Taillefer",
          "courriel": "jp.saab.02@example.com",
          "telephone": "613-851-0080",
          "telephoneUrgence": "6137963359",
          "adresse": "6252 Sablewood Place",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 7M5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Maeva ",
          "age": 7,
          "besoinsSpeciaux": "Serait-ce possible de la mettre dans le meme groupe que Hazel Crofton svp? Merci"
        },
        {
          "id": 26,
          "prenom": "Elizabeeth",
          "nom": "Murebwayire",
          "courriel": "ferniegirl@example.com",
          "telephone": "613-262-4565",
          "telephoneUrgence": "613-762-5565",
          "adresse": "6700 B Jeanne D'Arc Blvd Nord",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C 6E9",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Benedict ",
          "age": 5,
          "besoinsSpeciaux": "allergique au lait, ble, noix, arachide"
        },
        {
          "id": 27,
          "prenom": "Isabelle",
          "nom": "Marava",
          "courriel": "imcca050@example.com",
          "telephone": "6142621435",
          "telephoneUrgence": "6132506671",
          "adresse": "2418 Glandriel cres",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "J4A4T2",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Jacob ",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 28,
          "prenom": "Claire",
          "nom": "Castilla",
          "courriel": "claire.tugault@example.com",
          "telephone": "2288258280",
          "telephoneUrgence": "2502267579",
          "adresse": "6236 St. Albans Court",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 3C4",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Elizabeth ",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 29,
          "prenom": "Melanie",
          "nom": "Kanyenyeri",
          "courriel": "melboulerice@example.com",
          "telephone": "6138666352",
          "telephoneUrgence": "3535502900",
          "adresse": "1748 Teakdale",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 6M2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Laurianne ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 30,
          "prenom": "Joelle",
          "nom": "Avignon",
          "courriel": "joelle.levac@example.com",
          "telephone": "6133236142",
          "telephoneUrgence": "6133236157",
          "adresse": "987 chantenay drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "Y2c2J0",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Mikael ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 31,
          "prenom": "Malorie",
          "nom": "Lafortune",
          "courriel": "malorie.bertrand@example.com",
          "telephone": "16132220108",
          "telephoneUrgence": "16132270192",
          "adresse": "1184 St. Mortiz Court",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 2B3",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Presley ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 32,
          "prenom": "Jodie",
          "nom": "Mes",
          "courriel": "JODIEMCGILCHRIST@example.COM",
          "telephone": "6138801128",
          "telephoneUrgence": "6132291172",
          "adresse": "525 cannes crescent",
          "numeroSuite": "cannes crescent",
          "ville": "ottawa",
          "province": "ON",
          "codePostal": "J4A5J6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Presley ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 33,
          "prenom": "Erika",
          "nom": "Leger",
          "courriel": "ebelloni11292@example.com",
          "telephone": "6135523538",
          "telephoneUrgence": "6137002000",
          "adresse": "1549 Forest Valley",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 6G",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Cole ",
          "age": 5,
          "besoinsSpeciaux": "He is from English house but is in French School- Des Pionniers. His comprehension is good but sometimes needs clarification in English"
        },
        {
          "id": 34,
          "prenom": "Karine",
          "nom": "Mansouri",
          "courriel": "karvetvut@example.com",
          "telephone": "6132403800",
          "telephoneUrgence": "6136010060",
          "adresse": "1723 Hunter's Run Drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C6W2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Cody",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 35,
          "prenom": "Marie-Pier",
          "nom": "Diarra",
          "courriel": "mariepier_bernard@example.com",
          "telephone": "6136062253",
          "telephoneUrgence": "5155765952",
          "adresse": "1784 vigneault",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2C2H4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Laurent ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 36,
          "prenom": "Frencheska",
          "nom": "Rwigamba",
          "courriel": "xfrenx@example.com",
          "telephone": "6132631466",
          "telephoneUrgence": "6132631566",
          "adresse": "1673 Country Walk Drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 0E1",
          "nombreEnfants": 3,
          "nomPremierEnfant": "Felix ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 37,
          "prenom": "Isabelle",
          "nom": "Cornel",
          "courriel": "i.lalonde@example.com",
          "telephone": "613-304-5600",
          "telephoneUrgence": "613-292-5292",
          "adresse": "1033 Unicorn avenue",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "J4A 4H6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Evelyne ",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 38,
          "prenom": "Julie",
          "nom": "Blazeski",
          "courriel": "Julielangevin10@example.com",
          "telephone": "810 213 4541",
          "telephoneUrgence": "6132525652",
          "adresse": "1429 Ridgegate Street",
          "numeroSuite": "Ridgegate Street",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 7N5",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Amari",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 39,
          "prenom": "Sarah",
          "nom": "Ntumba",
          "courriel": "cogansarah@example.com",
          "telephone": "613-454-2305",
          "telephoneUrgence": "6135552305",
          "adresse": "6144 Lariviere",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2W1C6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Hugo",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 40,
          "prenom": "Amelie",
          "nom": "Charlebois",
          "courriel": "amelie.maisonneuve@example.com",
          "telephone": "613-316-1225",
          "telephoneUrgence": "613-262-3323",
          "adresse": "6356 Larmond ave",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 2H6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Winifred ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 41,
          "prenom": "Chloe",
          "nom": "Pacheco",
          "courriel": "chloe.st-denis@example.ca",
          "telephone": "6138055222",
          "telephoneUrgence": "6132275222",
          "adresse": "1153 Ste-Agathe Pk",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 2B4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Alek ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 42,
          "prenom": "Stephanie",
          "nom": "Daley",
          "courriel": "Julielangevin10@example.com",
          "telephone": "3435482634",
          "telephoneUrgence": "3535527635",
          "adresse": "1718 Bellechasse Pl",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 6W3",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Felix ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 43,
          "prenom": "Angie",
          "nom": "Shouldice",
          "courriel": "pelletierangie@example.com",
          "telephone": "16133028524",
          "telephoneUrgence": "16133022525",
          "adresse": "617 Simoneau Way",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "J4A1P5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Maxwell",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 44,
          "prenom": "Elodie",
          "nom": "AHOUANGANNON",
          "courriel": "elodiebouvier12@example.com",
          "telephone": "6134081330",
          "telephoneUrgence": "6137153632",
          "adresse": "234 Gossamer St.",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "Y2w 0b2",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Vienna ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 45,
          "prenom": "Stephanie",
          "nom": "Gauthier",
          "courriel": "steff.tetreault@example.com",
          "telephone": "613-608-6013",
          "telephoneUrgence": "613-225-0650",
          "adresse": "1649 Orford crescent",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "J4A 1V5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Hazel ",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 46,
          "prenom": "KIM",
          "nom": "Gravel",
          "courriel": "kimzap87@example.com",
          "telephone": "6135018104",
          "telephoneUrgence": "6135012105",
          "adresse": "706 Princess Louise Drive",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A 2C1",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Loic",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 47,
          "prenom": "Veronique",
          "nom": "Boulerice",
          "courriel": "edouardmarava@example.com",
          "telephone": "6133224086",
          "telephoneUrgence": "6132629252",
          "adresse": "1005 Bateau Place",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C2N2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Richard",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 48,
          "prenom": "Salamat",
          "nom": "Cherilus",
          "courriel": "salamattabbasum@example.com",
          "telephone": "6135815628",
          "telephoneUrgence": "6132067975",
          "adresse": "514 knotridge",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Ontario",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Juliet ",
          "age": 8,
          "besoinsSpeciaux": "Pas de porc Nouriture halal"
        },
        {
          "id": 49,
          "prenom": "Ashlyn",
          "nom": "April",
          "courriel": "ashlyngroulx@example.com",
          "telephone": "6138584508",
          "telephoneUrgence": "6132525592",
          "adresse": "6453 Sugar Creek Way",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C 1Y1",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Maxime ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 50,
          "prenom": "Nathalie",
          "nom": "Loh",
          "courriel": "liamlukasboseph@example.com",
          "telephone": "6138056203",
          "telephoneUrgence": "6137995522",
          "adresse": "6121 Silverbirch Street",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2W 1C4",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Zoe ",
          "age": 9,
          "besoinsSpeciaux": "Autisme tres leger.  Jumeau de Lukas Joseph"
        },
        {
          "id": 51,
          "prenom": "Stephanie",
          "nom": "Chartrand",
          "courriel": "slburk4@example.com",
          "telephone": "2800326553",
          "telephoneUrgence": "5279250556",
          "adresse": "1615 O'Toole Road",
          "numeroSuite": "",
          "ville": "Cumberland",
          "province": "Ontario",
          "codePostal": "J4C 1N2",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Florence ",
          "age": 10,
          "besoinsSpeciaux": "Allergie aux noix"
        },
        {
          "id": 52,
          "prenom": "Natalie",
          "nom": "Charles Alexis",
          "courriel": "natalierozon@example.com",
          "telephone": "613-614-2688",
          "telephoneUrgence": "613-295-1950",
          "adresse": "1984 Summerfields Cres",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C 7B4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Isabelle ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 53,
          "prenom": "Azaid",
          "nom": "Andrews",
          "courriel": "ahabib83@example.com",
          "telephone": "6138642423",
          "telephoneUrgence": "6132523936",
          "adresse": "182 De La Crevasse",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2W 0R5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Kaleb",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 54,
          "prenom": "Fariba",
          "nom": "Rozak",
          "courriel": "fariba.vaziri@example.com",
          "telephone": "3430888088",
          "telephoneUrgence": "6135155076",
          "adresse": "1623",
          "numeroSuite": "Wainfleet street",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "Y2C 3G3",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Selena ",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 55,
          "prenom": "Jenna",
          "nom": "Kahrer",
          "courriel": "jwoermke@example.com",
          "telephone": "6135014240",
          "telephoneUrgence": "6135015250",
          "adresse": "1881 Montmere ave",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "J4A 0L&",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Mikaela ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 56,
          "prenom": "Madeleine",
          "nom": "Seguin",
          "courriel": "edouardmarava@example.com",
          "telephone": "613-602-3440",
          "telephoneUrgence": "613-692-3559",
          "adresse": "1159 St-Emmanuel Terr",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C 2J6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Elizabeth ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 57,
          "prenom": "Caroline",
          "nom": "Jovic",
          "courriel": "edouardmarava@example.com",
          "telephone": "6138080154",
          "telephoneUrgence": "6132055052",
          "adresse": "1031 Jubilation crt",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "J4A5J4",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Emile ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 58,
          "prenom": "Henry",
          "nom": "Bourbonnais",
          "courriel": "sylvestrehenry8@example.com",
          "telephone": "6134132812",
          "telephoneUrgence": "6132225717",
          "adresse": "818 Mercier Crescent",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "Y2w 0N6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Kalina",
          "age": 1,
          "besoinsSpeciaux": ""
        },
        {
          "id": 59,
          "prenom": "Caroline",
          "nom": "Mason",
          "courriel": "lemieux1972@example.com",
          "telephone": "6134245106",
          "telephoneUrgence": "6136171123",
          "adresse": "134 sweetvalley drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "J4A 1A4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Mikael ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 60,
          "prenom": "Andree-Anne",
          "nom": "Carroll",
          "courriel": "andreeanneroy@example.ca",
          "telephone": "6133553622",
          "telephoneUrgence": "6133553677",
          "adresse": "114 Helenium Lane",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A 1C5",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Elias ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 61,
          "prenom": "Manon",
          "nom": "Bertrand",
          "courriel": "manon.gaudreau@example.com",
          "telephone": "613-316-0543",
          "telephoneUrgence": "613-316-0553",
          "adresse": "1721 Terrace des Broussailles",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C5T3",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Zacharie ",
          "age": 8,
          "besoinsSpeciaux": "Demande speciale svp : Semaine du 24 juin avec Oli Gauthier Semaine du 29 juillet avec Theodore Theriault"
        },
        {
          "id": 62,
          "prenom": "STEPHANIE",
          "nom": "Audet",
          "courriel": "mnscharlebois@example.com",
          "telephone": "6136016066",
          "telephoneUrgence": "6116016066",
          "adresse": "1710 Laurelwood Place",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2C6Y0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Zachary ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 63,
          "prenom": "Valerie",
          "nom": "Menard",
          "courriel": "val.taillefer@example.com",
          "telephone": "613-224-0502",
          "telephoneUrgence": "613-261-0592",
          "adresse": "1025 Jubilation Court",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "J4A 5J4",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Maeva ",
          "age": 8,
          "besoinsSpeciaux": ""
        },
        {
          "id": 64,
          "prenom": "Nadine",
          "nom": "LaPlante",
          "courriel": "nadine.murebwayire@example.com",
          "telephone": "6134006000",
          "telephoneUrgence": "6132227236",
          "adresse": "1027 jubilation crt orleans",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "J4a5J4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Benedict ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 65,
          "prenom": "Edouard",
          "nom": "Camire-Tremblay",
          "courriel": "edouardmarava@example.com",
          "telephone": "343 262-3406",
          "telephoneUrgence": "613-915-2316",
          "adresse": "999 shefford road",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2J6X6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Jacob ",
          "age": 4,
          "besoinsSpeciaux": "regulation emotionnelle parfois"
        },
        {
          "id": 66,
          "prenom": "Marie-Claire",
          "nom": "Nesbitt",
          "courriel": "marieclaire.castilla@example.com",
          "telephone": "613-850-8311",
          "telephoneUrgence": "613-259-2311",
          "adresse": "193 Cheyenne Way",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J2J 5S6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Arthur ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 67,
          "prenom": "Melanie",
          "nom": "Fournier",
          "courriel": "edouardmarava@example.com",
          "telephone": "3432224030",
          "telephoneUrgence": "3537775939",
          "adresse": "607 falwyn cres",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A 2B4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Laurianne ",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 68,
          "prenom": "Iryna",
          "nom": "Santos",
          "courriel": "iavignon@example.fr",
          "telephone": "6135018208",
          "telephoneUrgence": "6135012292",
          "adresse": "532, Salzburg Dr",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "On",
          "codePostal": "J4A0C6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Mikael ",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 69,
          "prenom": "Cynthia",
          "nom": "Sauve",
          "courriel": "cynthia.lafortune@example.com",
          "telephone": "6133218283",
          "telephoneUrgence": "6139155532",
          "adresse": "533 Salzburg Drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "J4a 0c6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Neve de ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 70,
          "prenom": "Becky",
          "nom": "Raffel",
          "courriel": "becky.mes@example.com",
          "telephone": "6138418688",
          "telephoneUrgence": "6135212106",
          "adresse": "1402 Forest Valley Dr",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2c5m0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Presley ",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 71,
          "prenom": "Louise",
          "nom": "Hebert",
          "courriel": "Louisevleger@example.com",
          "telephone": "6133045225",
          "telephoneUrgence": "6132966203",
          "adresse": "1405 Forest Valley drive",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C5M0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Cole ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 72,
          "prenom": "Hajar",
          "nom": "Lalonde",
          "courriel": "h.mansouri@ensem.ac.ma",
          "telephone": "2.12662E+11",
          "telephoneUrgence": "2.12663E+11",
          "adresse": "4 BUTTERNUT COURT",
          "numeroSuite": "",
          "ville": "OTTAWA",
          "province": "Ontario",
          "codePostal": "Y2B 4T6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Cody",
          "age": 10,
          "besoinsSpeciaux": ""
        },
        {
          "id": 73,
          "prenom": "Jessica",
          "nom": "Jasmin",
          "courriel": "keffi.jessica@example.com",
          "telephone": "8106302281",
          "telephoneUrgence": "2195762055",
          "adresse": "1060 Crois St-Germain",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "Y2C 2L0",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Hugo",
          "age": 8,
          "besoinsSpeciaux": ""
        },
        {
          "id": 74,
          "prenom": "Kayitesi Laura",
          "nom": "castilla",
          "courriel": "kaurla06@example.com",
          "telephone": "6132262010",
          "telephoneUrgence": "6132632056",
          "adresse": "109 destiny private",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A0J6",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Winifred ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 75,
          "prenom": "Stephanie",
          "nom": "Carriere Lalonde",
          "courriel": "stephanie.l8226@example.com",
          "telephone": "6132032266",
          "telephoneUrgence": "6137937266",
          "adresse": "1603 Meadowfield",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "On",
          "codePostal": "Y2c5v0",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Lucien",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 76,
          "prenom": "Sofi",
          "nom": "Donais",
          "courriel": "Blazeski_sofi@example.com",
          "telephone": "4163151430",
          "telephoneUrgence": "6132669322",
          "adresse": "525 Cannes crescent",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A 5j6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Felix ",
          "age": 5,
          "besoinsSpeciaux": "Asthma"
        },
        {
          "id": 77,
          "prenom": "Marthe",
          "nom": "Saab",
          "courriel": "ntumbamarthe000@example.com",
          "telephone": "613-203-0362",
          "telephoneUrgence": "613-793-0367",
          "adresse": "245 sweetvalley dr",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "J4A5J2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Maxwell",
          "age": 9,
          "besoinsSpeciaux": "ils ont recu une place de la part du CECCE."
        },
        {
          "id": 78,
          "prenom": "Laure",
          "nom": "Mason",
          "courriel": "Chalau05@example.com",
          "telephone": "16138620535",
          "telephoneUrgence": "6132665176",
          "adresse": "420, Crestview Rd",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "Y2H5G9",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Vienna ",
          "age": 8,
          "besoinsSpeciaux": ""
        },
        {
          "id": 79,
          "prenom": "Trisha",
          "nom": "McCauley",
          "courriel": "trishapacheco90@example.com",
          "telephone": "6132551808",
          "telephoneUrgence": "6132551292",
          "adresse": "595 pocono",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A3J6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Elizabeth ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 80,
          "prenom": "Rachelle",
          "nom": "Tugault-Lafleur",
          "courriel": "rachelle.daley@example.com",
          "telephone": "3062606038",
          "telephoneUrgence": "3062503539",
          "adresse": "2250",
          "numeroSuite": "Des Grands Champs",
          "ville": "Orleans",
          "province": "On",
          "codePostal": "Y2W 1Y2",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Loic",
          "age": 9,
          "besoinsSpeciaux": ""
        },
        {
          "id": 81,
          "prenom": "Kate",
          "nom": "Boulerice",
          "courriel": "kate_shouldice@example.com",
          "telephone": "613-880-3210",
          "telephoneUrgence": "613-295-5973",
          "adresse": "1803 Belval Crescent",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 6J5",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Gabriel",
          "age": 7,
          "besoinsSpeciaux": "TDAH, a besoin des medicaments en liquide dans l'apres midi"
        },
        {
          "id": 82,
          "prenom": "SIDONIE",
          "nom": "Levac-Laplante",
          "courriel": "kin_toucoul@example.com",
          "telephone": "4382645226",
          "telephoneUrgence": "6135052756",
          "adresse": "2205 Esprit drive K4A 4Z1 Orleans",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "Ontario",
          "codePostal": "J4A 4Z1",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Juliet ",
          "age": 5,
          "besoinsSpeciaux": ""
        },
        {
          "id": 83,
          "prenom": "Julie",
          "nom": "Bertrand",
          "courriel": "julie8bb@example.com",
          "telephone": "613-408-2204",
          "telephoneUrgence": "613-297-7522",
          "adresse": "2237 esprit drive orleans",
          "numeroSuite": "",
          "ville": "ottawa",
          "province": "on",
          "codePostal": "J4a4z4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Maxime ",
          "age": 8,
          "besoinsSpeciaux": ""
        },
        {
          "id": 84,
          "prenom": "Melanie",
          "nom": "Boyer",
          "courriel": "graveme@example.ca",
          "telephone": "613-218-1114",
          "telephoneUrgence": "613-229-9913",
          "adresse": "149 Hidden Valley Pvt",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 7P4",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Zoe ",
          "age": 8,
          "besoinsSpeciaux": ""
        },
        {
          "id": 85,
          "prenom": "Melanie et Jean-Marc",
          "nom": "Hendriks",
          "courriel": "melboulerice@example.com",
          "telephone": "6138666352",
          "telephoneUrgence": "3535502900",
          "adresse": "3436 Sarsfield Rd",
          "numeroSuite": "",
          "ville": "Sarsfield",
          "province": "ON",
          "codePostal": "J0A 3E0",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Florence ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 86,
          "prenom": "Bobyca",
          "nom": "Vetvutanapibul",
          "courriel": "cherboby94@example.com",
          "telephone": "3436301008",
          "telephoneUrgence": "5155165056",
          "adresse": "6059 Ridgelea Place",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "ON",
          "codePostal": "Y2C 5P9",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Isabelle ",
          "age": 4,
          "besoinsSpeciaux": ""
        },
        {
          "id": 87,
          "prenom": "Rhonda",
          "nom": "Bernard",
          "courriel": "rhonda.april@example.com",
          "telephone": "6138823605",
          "telephoneUrgence": "6132223695",
          "adresse": "500 Brisebois Cres",
          "numeroSuite": "",
          "ville": "Orleans",
          "province": "Ontario",
          "codePostal": "Y2E 0A6",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Laken",
          "age": 6,
          "besoinsSpeciaux": ""
        },
        {
          "id": 88,
          "prenom": "Natalie",
          "nom": "Bergeron",
          "courriel": "natliz_loh@example.com",
          "telephone": "6132425062",
          "telephoneUrgence": "6132296260",
          "adresse": "453 vinette",
          "numeroSuite": "453 vinette",
          "ville": "Hammond",
          "province": "Ontario",
          "codePostal": "J0a2a0",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Selena ",
          "age": 7,
          "besoinsSpeciaux": ""
        },
        {
          "id": 89,
          "prenom": "Maryse",
          "nom": "Lalonde Hendriks",
          "courriel": "marysechart1@example.com",
          "telephone": "6132640204",
          "telephoneUrgence": "6132195216",
          "adresse": "1377 Toulon Street",
          "numeroSuite": "",
          "ville": "Ottawa",
          "province": "ON",
          "codePostal": "Y2E1J2",
          "nombreEnfants": 1,
          "nomPremierEnfant": "Mikaela ",
          "age": 11,
          "besoinsSpeciaux": ""
        },
        {
          "id": 90,
          "prenom": "Jocelene",
          "nom": "Langevin",
          "courriel": "joalexis@myyahoo.com",
          "telephone": "6134102808",
          "telephoneUrgence": "2193192595",
          "adresse": "797 de Salaberry St.",
          "numeroSuite": "",
          "ville": "Gloucester",
          "province": "Ontario",
          "codePostal": "Y2J6Y5",
          "nombreEnfants": 2,
          "nomPremierEnfant": "Elizabeth ",
          "age": 5,
          "besoinsSpeciaux": ""
        }
       ]

const Student = {
  id: null,
  prenom: '',
  nom: '',
  courriel: '',
  telephone: '',
  telephoneUrgence: '',
  adresse: '',
  numeroSuite: '',
  ville: '',
  province: '',
  codePostal: '',
  nombreEnfants: 1,
  nomPremierEnfant: '',
  age: null,
  besoinsSpec: '',
  status: 'Absent',
}

const Attendance = () => {
  const [attendanceData, setAttendanceData] = useState([]);

  useEffect(() => {
    fetchAttendanceData();
  }, []);

  const fetchAttendanceData = async () => {
    try {
      const response = await axios.get('http://localhost:4000/users');
      const data = response.data.map(item => ({
        ...Student,
        ...item,
        status: 'Absent',	// Default status
      })).sort((a, b) => {
        const nameA = a.nom.toLowerCase();
        const nameB = b.nom.toLowerCase();
        if (nameA < nameB) return -1;
        if (nameA > nameB) return 1;
        return 0;
      });
      setAttendanceData(data);
      console.log(`my name os helga : ${JSON.stringify(data)}`);
    } catch (err) {
      // This is a temporary fix since backend is not live yet
      if (err.code === 'ERR_NETWORK' && attendanceData.length === 0) {
        setAttendanceData(userData);
      }
      console.error('Error fetching attendance data:', err);
    }
  };

  const toggleAttendance = (studentId) => {
    setAttendanceData(prevData =>
      prevData.map(student =>
        student.id === studentId
          ? { ...student, status: student.status === 'Present' ? 'Absent' : 'Present' }
          : student
      )
    );
  };

  const markAllAttendance = (status) => {
    setAttendanceData(prevData =>
      prevData.map(student => ({ ...student, status }))
    );
  };

  return (
    <div>
      <h1>Attendance Sheet</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        {attendanceData && (
          <tbody>
          {attendanceData.map(student => (
            <tr key={student.id}>
              <td>{student.nom}, {student.prenom}</td>
              <td>{student.status}</td>
                <td>
                <div className="toggle-switch">
                    <input
                      type="checkbox"
                      className="checkbox"
                      checked={student.status === 'Present'}
                      onChange={() => toggleAttendance(student.id)}
                    />
                    <label className="label">
                      <span className="inner" />
                      <span className="switch" />
                    </label>
                  </div>
                </td>
            </tr>
          ))}
        </tbody>
        )}
      </table>
      <div className="attendance-actions">
        <button onClick={() => markAllAttendance('Present')}>Mark All Present</button>
        <button >Submit</button>
      </div>
    </div>
  );
};

export default Attendance;